# Generated by Django 6.0.3 on 2026-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(verbose_name='Категория')),
                ('designation', models.CharField(verbose_name='Обозначение/Артикуль')),
                ('diameter_dn', models.IntegerField(verbose_name='Условный проход')),
                ('pressure_pn', models.IntegerField(verbose_name='Условное давление')),
                ('material', models.CharField(verbose_name='Материал')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
    ]
