# Generated by Django 5.2.12 on 2026-03-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_alter_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
    ]
